//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBasedApproach.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEmployeeDetail", Namespace="http://tempuri.org/", ItemName="employeeDetail")]
    [System.SerializableAttribute()]
    public class ArrayOfEmployeeDetail : System.Collections.Generic.List<ModelBasedApproach.ServiceReference1.employeeDetail> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="employeeDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class employeeDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNameField;
        
        private System.Nullable<int> EmpSalaryField;
        
        private System.Nullable<int> DeptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private System.Nullable<System.DateTime> dobField;
        
        private bool StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EmpName {
            get {
                return this.EmpNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNameField, value) != true)) {
                    this.EmpNameField = value;
                    this.RaisePropertyChanged("EmpName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> EmpSalary {
            get {
                return this.EmpSalaryField;
            }
            set {
                if ((this.EmpSalaryField.Equals(value) != true)) {
                    this.EmpSalaryField = value;
                    this.RaisePropertyChanged("EmpSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> DeptId {
            get {
                return this.DeptIdField;
            }
            set {
                if ((this.DeptIdField.Equals(value) != true)) {
                    this.DeptIdField = value;
                    this.RaisePropertyChanged("DeptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> dob {
            get {
                return this.dobField;
            }
            set {
                if ((this.dobField.Equals(value) != true)) {
                    this.dobField = value;
                    this.RaisePropertyChanged("dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CalculatorSoap")]
    public interface CalculatorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ModelBasedApproach.ServiceReference1.HelloWorldResponse HelloWorld(ModelBasedApproach.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelBasedApproach.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ModelBasedApproach.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        // CODEGEN: Generating message contract since element name GetEmployeeModelsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeModels", ReplyAction="*")]
        ModelBasedApproach.ServiceReference1.GetEmployeeModelsResponse GetEmployeeModels(ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeModels", ReplyAction="*")]
        System.Threading.Tasks.Task<ModelBasedApproach.ServiceReference1.GetEmployeeModelsResponse> GetEmployeeModelsAsync(ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ModelBasedApproach.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ModelBasedApproach.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelBasedApproach.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ModelBasedApproach.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeModelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeModels", Namespace="http://tempuri.org/", Order=0)]
        public ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequestBody Body;
        
        public GetEmployeeModelsRequest() {
        }
        
        public GetEmployeeModelsRequest(ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeModelsRequestBody {
        
        public GetEmployeeModelsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeModelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeModelsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModelBasedApproach.ServiceReference1.GetEmployeeModelsResponseBody Body;
        
        public GetEmployeeModelsResponse() {
        }
        
        public GetEmployeeModelsResponse(ModelBasedApproach.ServiceReference1.GetEmployeeModelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeModelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ModelBasedApproach.ServiceReference1.ArrayOfEmployeeDetail GetEmployeeModelsResult;
        
        public GetEmployeeModelsResponseBody() {
        }
        
        public GetEmployeeModelsResponseBody(ModelBasedApproach.ServiceReference1.ArrayOfEmployeeDetail GetEmployeeModelsResult) {
            this.GetEmployeeModelsResult = GetEmployeeModelsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorSoapChannel : ModelBasedApproach.ServiceReference1.CalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorSoapClient : System.ServiceModel.ClientBase<ModelBasedApproach.ServiceReference1.CalculatorSoap>, ModelBasedApproach.ServiceReference1.CalculatorSoap {
        
        public CalculatorSoapClient() {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelBasedApproach.ServiceReference1.HelloWorldResponse ModelBasedApproach.ServiceReference1.CalculatorSoap.HelloWorld(ModelBasedApproach.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ModelBasedApproach.ServiceReference1.HelloWorldRequest inValue = new ModelBasedApproach.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ModelBasedApproach.ServiceReference1.HelloWorldRequestBody();
            ModelBasedApproach.ServiceReference1.HelloWorldResponse retVal = ((ModelBasedApproach.ServiceReference1.CalculatorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelBasedApproach.ServiceReference1.HelloWorldResponse> ModelBasedApproach.ServiceReference1.CalculatorSoap.HelloWorldAsync(ModelBasedApproach.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelBasedApproach.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ModelBasedApproach.ServiceReference1.HelloWorldRequest inValue = new ModelBasedApproach.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ModelBasedApproach.ServiceReference1.HelloWorldRequestBody();
            return ((ModelBasedApproach.ServiceReference1.CalculatorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModelBasedApproach.ServiceReference1.GetEmployeeModelsResponse ModelBasedApproach.ServiceReference1.CalculatorSoap.GetEmployeeModels(ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequest request) {
            return base.Channel.GetEmployeeModels(request);
        }
        
        public ModelBasedApproach.ServiceReference1.ArrayOfEmployeeDetail GetEmployeeModels() {
            ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequest inValue = new ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequest();
            inValue.Body = new ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequestBody();
            ModelBasedApproach.ServiceReference1.GetEmployeeModelsResponse retVal = ((ModelBasedApproach.ServiceReference1.CalculatorSoap)(this)).GetEmployeeModels(inValue);
            return retVal.Body.GetEmployeeModelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModelBasedApproach.ServiceReference1.GetEmployeeModelsResponse> ModelBasedApproach.ServiceReference1.CalculatorSoap.GetEmployeeModelsAsync(ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequest request) {
            return base.Channel.GetEmployeeModelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModelBasedApproach.ServiceReference1.GetEmployeeModelsResponse> GetEmployeeModelsAsync() {
            ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequest inValue = new ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequest();
            inValue.Body = new ModelBasedApproach.ServiceReference1.GetEmployeeModelsRequestBody();
            return ((ModelBasedApproach.ServiceReference1.CalculatorSoap)(this)).GetEmployeeModelsAsync(inValue);
        }
    }
}
